fix: react-modal import error
fix the following error:
```
src/ModalComponent.tsx:9:8 - error TS1259: Module '"/home/philippe/Projects/EODAG/eodag-labextension-legacy/node_modules/@types/react-modal/index"' can only be default-imported using the 'esModuleInterop' flag

9 import Modal, { Styles } from 'react-modal';
         ~~~~~

  node_modules/@types/react-modal/index.d.ts:17:1
    17 export = ReactModal;
       ~~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
```